### ISSUE TITLE
Add the project to the listing at https://openapi.tools/

### ISSUE THREAD

**Issue by gregorwolf** [abap-openapi/abap-openapi#86]
Hi @larshp,

what do you think about adding the project to:

https://openapi.tools/

This is done as described in their [CONTRIBUTING.md](https://github.com/apisyouwonthate/openapi.tools/blob/main/CONTRIBUTING.md).

CU
Gregor

**Comment by larshp** [comment]
sure, feel free if you have time

**Comment by gregorwolf** [comment]
Got this suggestion from https://twitter.com/ajmrdg who will give a SAP TechEd talk on "OpenAPIs in the SAP Ecosystem". I've brought this project to his attention.

**Comment by larshp** [comment]
cool 👍

**Comment by gregorwolf** [comment]
Based on their [categories.yml](https://github.com/apisyouwonthate/openapi.tools/blob/main/_data/categories.yml) I would think the best fit is:

- SDK Generators
- Server Implementations

**Comment by gregorwolf** [comment]
What do you think about:

```yaml
- name: ABAP OpenAPI Client & Server Generator
  category:
    - sdk
    - server
  language: ABAP
  github: https://github.com/abap-openapi/abap-openapi 
  link: https://abap-openapi.github.io/web-openapi-client/
  description: 
    ABAP OpenAPI Client & Server Generator written in ABAP. 
    Runs also in the Browser and on command line using NodeJS.
    Creates one self-contained global class + interface per OpenAPI definition.
  v2: true
  v3: true
```
